FROM node:20.18.0-alpine AS build
WORKDIR /app
COPY apps/admin/package*.json ./
RUN npm ci
COPY packages/api-client /packages/api-client
COPY apps/admin/ .
ARG VITE_API_URL=/api/v1
ARG VITE_BASE_PATH=/admin/
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_BASE_PATH=$VITE_BASE_PATH
RUN npm run build

FROM nginx:1.27.4-alpine
COPY apps/admin/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
